version: 0.2

phases:
  build:
    commands:
      - if [ $CODEBUILD_WEBHOOK_EVENT == "PULL_REQUEST_CREATED" ]; then aws s3 cp index.html s3://codebuild-beta/index.html; fi
      - if [ $CODEBUILD_WEBHOOK_EVENT == "PULL_REQUEST_MERGED" ]; then aws s3 cp index.html s3://codebuild-prod515/index.html; fi
